sudo: required
language: bash
services:
- docker
before_script:
- docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
- docker-compose build sapi-python-client
script:
- docker-compose run --rm --entrypoint=flake8 sapi-python-client
- docker-compose run --rm -e KBC_TEST_TOKEN -e KBC_TEST_API_URL sapi-python-client -m unittest discover
- docker-compose run --rm -e KBC_TEST_TOKEN=$KBC_AZ_TEST_TOKEN -e KBC_TEST_API_URL=$KBC_AZ_TEST_API_URL sapi-python-client -m unittest discover
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notifications:
  slack:
    rooms:
      secure: IHfa2pHnjC/lY3H4062fTTz7y1CmHw0FbVtyxG8mMD9iuAbEIvgOs8+BRLFzqx6Baej1TnELFek7QCFdMV5SVDda7XMCOY5WLMoG1YoQ4UtnYE2mhvEsoKEu5C73rZ/OIm1jIihLFGpznwhq+ZSbPT2wiKfJglic87NW5XPsYE52XvZRQ3RY0dZpTxpXIdKOKUvcMK0FZfzDbkGHOB8GTVRNyaa1r4uI4XTyNW3c3l8sTOQo3l4rCtQXyMVqWIKXywxSfo7r+h1XPqrxpUtm+2d/B05bYRlD39OGR3O5LwK1YDFl7F3Dc9u503IhMs1p5gc3jRb4L1QCJXy0VcXgHPyaKMSnE6Ambja6S8oXXao167iR7qJ3sHgd1PAs48pSZPoqSvVB8K26X59l9jKf0xAqFm2tZVEOuYD2yGKoWpB4f201yTfVQaQ69P/lLFhao+kI2XuupCgyVTeuOFyc4fYS6k1ooJvFY8NPlhnCVW6xYJCfRcy0gYFXCAVgqpl6Icm4nMVQ66AU6tQckfuZK/7vfpw1SsfifeHLFLQp0AiXydS4ozhFYzejDxVnKH8a1S4ZGfvgPEVfc2xp5C8nJR8YJn9KA3V0JJ01foBofymWnB2QPLUQr3iaLbPsep3ixtjxTSTTjFWCv5kd6Sh193KcK/0RkHWs+1Tz0Lb+FZM=
